version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
    assignees:
      - 5h0utat0t2uka

  - package-ecosystem: "npm"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    assignees:
      - 5h0utat0t2uka
